services:
  taskgraph:
    container_name: taskgraph
    build:
      context: .
      dockerfile: debug/Dockerfile
    command: sh -c 'goose postgres "host=$${POSTGRES_HOST} port=5436 user=$${POSTGRES_USER} password=$${POSTGRES_PASSWORD} dbname=$${POSTGRES_DB} sslmode=$${POSTGRES_SSL_MODE}" up && go run cmd/app/main.go'
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    depends_on:
      taskgraph-db:
        condition: service_healthy

  taskgraph-db:
    container_name: taskgraph-db
    image: postgres:17
    restart: always
    ports:
      - "5436:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
